project:
  type: book
  output-dir: _site

book:
  title: "Math in C"
  author: "Dankao Chen"
  language: zh
  page-navigation: true
  chapters:
    - index.qmd
    - part: "基础"
      chapters:
        - notebooks/01-basics.ipynb

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    page-layout: full
