services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/project
    command: jupyter lab --ip=0.0.0.0 --no-browser --ServerApp.token='' --ServerApp.root_dir=/project

  quarto:
    build:
      context: .
      dockerfile: Dockerfile.quarto
    ports:
      - "4444:4444"
    volumes:
      - .:/project
    working_dir: /project
    command: quarto preview --port 4444 --host 0.0.0.0 --no-browser
